
module.exports=(sequelize,Sequelize)=>{
    const model=sequelize.define('usertbl',{
        id:{
            type:Sequelize.INTEGER,
            autoIncrement:true,
            allowNull:false,
            primaryKey:true
        },
        name:{
            type:Sequelize.STRING(100),
            allowNull:false
        },
        mobile:{
            type:Sequelize.STRING(12),
            allowNull:false
        },
        email:{
            type:Sequelize.STRING(20),
            allowNull:true,
            unique:true
        },
        password:{
            type:Sequelize.STRING(100),
            allowNull:false,
        },
        isActive:{
            type:Sequelize.BOOLEAN,
            defaultValue:true
        }
    },{
        freezeTableName:true,
        //timestamps:false,
        timestamps:true,
        createdAt:false,
        updatedAt:false
    })
    return model;
}